#trigger: none

resources:
- repo: self
queue:
  name: Hosted Ubuntu 1604

variables:
- group: testGroup

parameters:
- name: myNumber

steps:
- task: UsePythonVersion@0
  displayName: 'Use Python 3.6'
  inputs:
    versionSpec: 3.6

- script: |
    python -m pip install --upgrade pip
    pip install -r requirements.txt
  displayName: 'Install dependencies'

- task: PythonScript@0
  inputs: 
    scriptPath: 'run1.py'
    # arguments: ${{ parameters.myNumber }}

